''' Renumber files in ascending order numerically: To be used to reorder 
dump image files generated by lammmps to create movie with ffmpeg '''

import os

# Modify these if needed, files are named <root>*<ext>
root = 'dump'
ext = '.jpg'

def sort_key(filename):
	return int(filename.split(root)[1].split(ext)[0])

files = [f for f in os.listdir() if f.endswith(ext)]

# Sort
files = sorted(files, key = sort_key)

# Rename
for i in range(len(files)):
	newname = root + str(i) + ext
	os.rename(files[i],newname)

print('Done')
